### ISSUE TITLE
Save thumbnails in a decentral way

### ISSUE THREAD

**Issue by ben221199** [OdyseeTeam/e-mage#1]
Hello all,

When uploading a video to Odysee, it seems that the thumbnail is uploaded to a central server and its URL is put in the thumbnail source url (https://github.com/lbryio/types/blob/master/v2/proto/claim.proto#L62). However, this isn't optimal when other video platforms want to serve the same content, but want to have their own thumbnail server too. Luckily, in v2 of the LBRY metadata it is also possible to add decentral hashes for thumbnails (https://github.com/lbryio/types/blob/master/v2/proto/claim.proto#L57). Can this be fixed, so that Odysee will use the decental solution? Problem with the current solution is that you need to check periodically if the thumbnail has changed, because technically thumbnails can be changed without changing the URL. When using hashes, this is not the case. If the thumbnail changes, the hash changes too.

Thanks in advance

**Comment by tzarebczan** [comment]
Thanks for the suggestion, but we don’t have any plans on changing this at the moment. 

The thumbnail cannot change however, if that’s one of the main concerns.

**Comment by ben221199** [comment]
The problem is that such trust is only valid in case of Odysee. Other platforms can enter their own URLs there, but don't have to follow those "untold" rules. For now, I will look for some solution to it.

@tzarebczan If other platforms use the thumbnail source hash, instead of the thumbnail source URL, are those thumbnails visible on Odysee or does the problem occur that Odysee only looks to the URL and hash-thumbnails will be not visible?
